### ISSUE TITLE
No "pep8: Lint" command in my command palette?

### ISSUE THREAD

**Issue by nlsn** [tarnfeld/atom-pep8#10]
I'm new to Atom, so I'm probably doing something foolish… but when I open the command palette and type "pep8" I find nothing.

In the console (ctrl-shift-i) I see this:

```
activate linter-python-pep8
```

How do I trigger the pep8 linting?

**Comment by tarnfeld** [comment]
Do you have pep8 installed on your machine? The default path used by the plugin is `/usr/local/bin/pep8` so check there first. You can configure the path through the settings if it's installed elsewhere.

Also, have you tried checking the "Lint On Save" configuration option?

**Comment by nlsn** [comment]
Yes. I have pep8 installed in `c:\Users\nabrown\AppData\Local\Continuum\Anaconda\Scripts` and that's the setting I have for `P E P8 Path` for this package. I also tried specifying the executable with the path: `c:\Users\nabrown\AppData\Local\Continuum\Anaconda\Scripts\pep8.exe`.

The only settings I have are `P E P8 Path` and `Ignore Errors`. I don't see a setting in this package for "Lint On Save", but I have that selected in the main Linter package already.

When I save, I see this error:

```
Uncaught Error: spawn c:\Users\nabrown\AppData\Local\Continuum\Anaconda\Scripts ENOENT
events.js:85
Hide Stack TraceShow Stack Trace
Error: spawn c:\Users\nabrown\AppData\Local\Continuum\Anaconda\Scripts ENOENT
  at exports._errnoException (util.js:742:11)
  at Process.ChildProcess._handle.onexit (child_process.js:1051:32)
  at child_process.js:1142:20
  at process._tickCallback (node.js:378:11)
```

I switched to using this PEP8 linter instead, and I'm happy with the automatic checking, rather than initiating with command or saving:
https://github.com/AtomLinter/linter-pep8

Thanks for the response, but the issue is moot from my point of view.

**Comment by tarnfeld** [comment]
:+1: Thanks for the details! I'm not really using Atom anymore anyway so am not maintaining this too much myself, plus I never tested it on Windows.

**Comment by nlsn** [comment]
For what it's worth, it worked fine on my Ubuntu box.

**Comment by tarnfeld** [comment]
Ah, it wouldn't surprise me if I've not done something correctly for Windows then. Thanks for the detailed report!
