### ISSUE TITLE
Saving causes cursor to jump to the first pep8 violation.

### ISSUE THREAD

**Issue by shylux** [tarnfeld/atom-pep8#2]
I am working on a community project which contains a lot of pep8 violations. Now if i save the document the pep8 validation gets executed. The first violation get the focus and the cursor jumps to this line. I have to scroll down to my code every time i save.

You may argue that this is the expected behavior, but i find it quite annoying. 

It would be great if you could make the validation on safe configurable.

**Comment by tarnfeld** [comment]
I agree :thumbsup: so i'm going to get this implemented.

**Comment by shylux** [comment]
👍
