### ISSUE TITLE
Is a restart required?

### ISSUE THREAD

**Issue by peterbe** [tarnfeld/atom-pep8#3]
If not, it's not working. I installed it and made sure the path is working. Screwed around in a .py file and tried to find pep8 in the command palette menu thing. Or, how else are you supposed to start it?

**Comment by peterbe** [comment]
Restart is not required. I just didn't know how to start it.

**Comment by kf0jvt** [comment]
So, how did you start it? I've been trying command+shift+p and then typing pep8 and getting nothing.

**Comment by cloughrm** [comment]
I'm having the same issue, installed atom-pep8, then tried a restart, and no pep8 command available in the command+shit+p menu

**Comment by kf0jvt** [comment]
Turns out that when you save a file it automatically kicks in. I never
found a way to start it other than saving a python file.
