### ISSUE TITLE
Let me decide when to pep8

### ISSUE THREAD

**Issue by peterbe** [tarnfeld/atom-pep8#4]
I installed atom-pep8 and started editing a file that has known flaws. Now's not the time to correct them. 

So I have my cursor on line, say, 100 and hit Cmd-S to save. That then brings up the 3 pep8 errors I have in that file. The first one is on line 150 so it moves my cursor down there to line 150. Annoying. 

I would personally much prefer to decide myself when to run pep8. Not on save but when **I** run it. 

Or, if it has to be on save, it shouldn't move the cursor.

**Comment by tarnfeld** [comment]
That's a good point, it'd be great to make this configurable. I originally modelled it from the PEP8 linter for Sublime Text which behaves in this way.

I personally prefer it to force me to pep8 since where I work most pep8 errors cause our test suites to fail, so it's handy :-)

**Comment by tarnfeld** [comment]
I'm going to close this in favour of #2
